# SPDX-License-Identifier: Apache-2.0
"""Person and private-residence screen for EPA ECHO facility names.

ECHO ``FAC_NAME`` is free text supplied by permitting programs. Some permits
cover a single private residence (for example a small-flow or single-residence
sewage system) and carry a household's name, a house-number street address, or
both. The ECHO projection declares ``person_or_contact`` and
``street_or_geolocation`` as excluded categories, so the ingestor rejects such
rows before serialization and both snapshot verifiers refuse a bundle that
still carries one.

The screen is a deterministic heuristic over the facility name and NAICS codes
only. It is not identity resolution: it can reject an organization whose name
reads like a person, and it can miss an unusual personal name. It uses the
standard library only because the Space image copies ``app/`` but not the
ingestion tooling, and the ingestor and the runtime must apply the same rule.
"""
from __future__ import annotations

import re
from typing import Iterable

REJECTION_REASON = "PERSON_OR_RESIDENCE_NAME"

PRIVATE_HOUSEHOLD_NAICS = "814110"  # NAICS: Private Households

# Residential permit designations and residence words. HOUSEHOLD is not
# counted when it introduces a household-hazardous-waste program.
_RESIDENTIAL = re.compile(
    r"\b(?:SRSTP|SFTF|SFS|SFR|HSTS|HOMEOWNER|RES|RESIDENCE|PROP"
    r"|SINGLE[\s-]+FAMILY|HOUSEHOLD(?![\s-]+HAZARDOUS))\b"
)

# Words that make a residential designation belong to an organization. Kept
# narrow on purpose: generic words such as COUNTY, CHURCH, SCHOOL, STATE, or CO
# also occur in road names and must not rescue a residence row.
_ORGANIZATION_MARKERS = frozenset(
    """
    LLC INC INCORPORATED CORP CORPORATION COMPANY LTD LLP LLLP LP PLLC
    ASSN ASSOC ASSOCIATION HOA POA CONDOMINIUM CONDO COOPERATIVE COOP
    HOTEL MOTEL INN RESORT SUITES MUNICIPAL MUNICIPALITY AUTHORITY
    """.split()
)
_GOVERNMENT_OF = re.compile(r"\b(?:CITY|TOWN|TOWNSHIP|BOROUGH|COUNTY|VILLAGE)\s+OF\b")

# A house number, an optional directional, one to three street-name words, and
# a street type. Seven-digit and longer numbers (parcel or permit numbers) and
# a number directly followed by a street type (for example "2 ST ...") do not
# match. A grid house number may carry a directional prefix (for example
# "W1234 EXAMPLE RD").
_STREET_ADDRESS = re.compile(
    r"(?<![0-9A-Z])[NSEW]?[0-9]{1,6}[A-Z]?\s+(?:[NSEW]\.?\s+)?"
    r"(?:[A-Z0-9'\-]+\.?\s+){1,3}"
    r"(?:ST|STREET|AVE|AVENUE|RD|ROAD|BLVD|BOULEVARD|DR|DRIVE|LN|LANE|HWY|HIGHWAY"
    r"|WAY|CT|COURT|PL|PLACE|PKWY|PARKWAY|CIR|CIRCLE|TER|TERRACE|TRL|TRAIL|PIKE"
    r"|TPKE|TURNPIKE|ROUTE|RT)\b"
)

# A house number of two to six digits followed by a numbered highway or route
# (for example "1234 STATE ROUTE 9", "1234 US 20", or "1234 CR K").
_ROUTE_ADDRESS = re.compile(
    r"(?<![0-9A-Z])[NSEW]?[0-9]{2,6}[A-Z]?\s+(?:[NSEW]\.?\s+)?"
    r"(?:(?:STATE|COUNTY|CO|CTY|US|ST)\.?\s+)?"
    r"(?:(?:HWY|HIGHWAY|ROUTE|RTE|RT|SR|CR|US)\.?\s+[0-9]{1,5}[A-Z]?"
    r"|(?:HWY|HIGHWAY|ROUTE|RTE|RT|SR|CR)\.?\s+[A-Z]{1,3})\b"
)

_DBA = re.compile(r"\b(?:D/?B/?A|T/?A|A/?K/?A)\b.*$")  # doing/trading as
_ESTATE_OF = re.compile(r"^(?:THE\s+)?(?:ESTATE|EST)\s+OF\s+")
_TOKEN_SPLIT = re.compile(r"[^A-Z0-9'&\-]+")
_NAME_WORD = re.compile(r"[A-Z]+(?:['\-][A-Z]+)*")
_DIGIT = re.compile(r"[0-9]")

# Courtesy titles that introduce a personal name ("MR SAMPLE", "MR & MRS
# SAMPLE", "DR JANE SAMPLE").
_HONORIFIC = re.compile(
    r"^(?:MR|MRS|MS|MISS|MESSRS|MMES|DR)\.?"
    r"(?:\s*(?:&|AND)\s*(?:MR|MRS|MS|MISS|DR)\.?)?\s+"
)

# Generational ordinals written with digits ("JANE SAMPLE 3RD").
_ORDINAL_AFFIX = re.compile(r"\b(?:2ND|3RD|4TH)\b")

# Designations that only a private individual or household carries: a
# personal trust, a decedent's estate, heirs, or "et al." / "et ux.".
_PERSON_MARKER = re.compile(
    r"\b(?:(?:LIVING|REVOCABLE|IRREVOCABLE|FAMILY)\s+TRUST|ESTATE\s+OF"
    r"|HEIRS(?:\s+OF)?|ET\.?\s*(?:AL|UX|VIR)\.?)(?![A-Z])"
)
_LEADING_THE = re.compile(r"^\s*THE\s+")

# Generational and credential affixes carried by personal names.
_NAME_AFFIXES = frozenset("JR SR II III IV MD DDS DVM DO ESQ CPA PHD RN".split())

# Sewage-system descriptors that follow a household name on residential
# discharge permits. They are removed before the person-shape test.
_SEPTIC_DESCRIPTORS = frozenset(
    "STP SEWAGE TREATMENT PLANT SYSTEM SEPTIC WWTP WWTF TP DISCHARGE".split()
)

# Words for a single dwelling. With at most three other words and no
# organization word, the name designates a private residence.
_RESIDENCE_WORDS = frozenset(
    "COTTAGE CABIN DWELLING DUPLEX TRIPLEX RESIDENTIAL HOMESITE HOMESTEAD".split()
)

# Common US given names (general knowledge, not an authoritative list). The
# first block is the original list. The second widens it to less frequent and
# older given names, including some that are also surnames or place names; a
# name that also carries an organization word is still admitted. Words that
# are mainly place, brand, or business words are left out.
_GIVEN_NAMES = frozenset(
    """
    JAMES JOHN ROBERT MICHAEL WILLIAM DAVID RICHARD JOSEPH THOMAS CHARLES
    CHRISTOPHER DANIEL MATTHEW ANTHONY DONALD STEVEN PAUL ANDREW JOSHUA KENNETH
    KEVIN BRIAN GEORGE TIMOTHY RONALD EDWARD JASON JEFFREY RYAN JACOB GARY
    NICHOLAS ERIC JONATHAN STEPHEN LARRY JUSTIN SCOTT BRANDON BENJAMIN SAMUEL
    GREGORY ALEXANDER PATRICK JACK DENNIS JERRY TYLER AARON JOSE ADAM NATHAN
    HENRY ZACHARY DOUGLAS PETER KYLE NOAH ETHAN JEREMY WALTER KEITH ROGER TERRY
    HAROLD SEAN CARL ARTHUR LAWRENCE DYLAN JESSE JORDAN BRYAN BILLY BRUCE
    GABRIEL JOE LOGAN ALBERT WILLIE ALAN EUGENE RUSSELL VINCENT PHILIP BOBBY
    JOHNNY BRADLEY ROY RALPH RANDY LOUIS HARRY WAYNE HOWARD FRED ERNEST MARTIN
    CRAIG STANLEY SHAWN TRAVIS PHILLIP LEONARD EARL DALE JIMMY RODNEY TODD
    NORMAN ALLEN MARVIN GLENN JEFFERY DARRELL CURTIS FRANCIS LEROY CLARENCE
    DERRICK FRANK DONNIE RICKY HERBERT MELVIN MIKE DAN DAVE TOM TONY JIM BOB
    STEVE RICK RICKEY RON KEN GREG JEFF DOUG CHUCK CHARLIE DANNY TOMMY TIM JON
    JOEY BEN SAM NICK MATT CHRIS PETE LUIS CARLOS JUAN MIGUEL JORGE PEDRO
    MANUEL FRANCISCO JESUS ANTONIO ALEJANDRO RAFAEL RAMON ROBERTO FERNANDO
    RICARDO EDUARDO JAVIER SERGIO MARIO HECTOR ANGELO VICTOR OSCAR ENRIQUE
    ARMANDO RAUL ALBERTO JULIO MOHAMMED MOHAMED MUHAMMAD AHMED ALI HASSAN OMAR
    KHALID RAJ SANJAY RAVI SURESH RAMESH VIJAY AMIT RAHUL ANIL WEI LI HUNG MINH
    TUAN DUC KIM MARY PATRICIA JENNIFER LINDA ELIZABETH BARBARA SUSAN JESSICA
    SARAH KAREN LISA NANCY BETTY SANDRA MARGARET ASHLEY KIMBERLY EMILY DONNA
    MICHELLE CAROL AMANDA MELISSA DEBORAH STEPHANIE DOROTHY REBECCA SHARON
    LAURA CYNTHIA KATHLEEN HELEN ANNA SHIRLEY ANGELA BRENDA PAMELA NICOLE
    SAMANTHA KATHERINE CHRISTINE DEBRA RACHEL CAROLYN JANET MARIA HEATHER DIANE
    JULIE JOYCE VICTORIA KELLY CHRISTINA JOAN EVELYN LAUREN JUDITH OLIVIA
    MARTHA CHERYL MEGAN ANDREA HANNAH JACQUELINE ANN JEAN ALICE KATHRYN GLORIA
    TERESA DORIS SARA JANICE JULIA MARIE MADISON JUDY THERESA BEVERLY DENISE
    MARILYN AMBER DANIELLE BRITTANY DIANA ABIGAIL JANE LORI TAMMY KAYLA ALEXIS
    TIFFANY WANDA TINA PEGGY LOIS BONNIE SHEILA PHYLLIS NORMA ELLEN MILDRED
    ESTHER ETHEL IRENE VIRGINIA RUTH LOUISE CONNIE PAULA ROBIN ANNE SUE SALLY
    DEBBIE CINDY KATHY KATIE BETH JILL JENNY BECKY PATTY VICKIE VICKI DEE
    DIANNE JOANN SHERRY TRACY TRACEY STACY STACEY KRISTEN KRISTIN ERIN EMMA
    ELLA SOPHIA ISABELLA AVA MIA CHLOE ZOE NATALIE LEAH AUDREY CLAIRE CARMEN
    ROSA ANA LUCIA GUADALUPE YOLANDA LETICIA VERONICA ALMA MARGARITA SILVIA
    ELENA PRIYA LAKSHMI SUNITA MEI YING LAN
    ABBY ABDUL ABDULLAH ABE ABEL ABNER ABRAHAM ADA ADDIE ADELE ADELINE ADOLFO
    ADOLPH ADRIAN ADRIANA ADRIENNE AGNES AGUSTIN AHMAD AIDEN AILEEN AIMEE ALANA
    ALDEN ALEC ALEJANDRA ALEX ALEXA ALEXANDRA ALFONSO ALFRED ALFREDO ALICIA
    ALISA ALISHA ALISON ALLAN ALLIE ALLISON ALLYSON ALONZO ALTA ALTON ALVARO
    ALVIN ALYSSA AMELIA AMIR AMOS AMY ANAND ANDRE ANDRES ANDY ANGEL ANGELICA
    ANGELINA ANGIE ANH ANITA ANNETTE ANNIE ANTOINE ANTOINETTE ANTON ANTONIA
    APRIL ARCHIE ARIANA ARLEN ARLENE ARLIN ARLO ARNOLD ARTURO ARUN ASHLEE
    ASHLEIGH ASHOK AUBREY AUDRA AUGUSTINE AUGUSTUS BARB BARRY BART BASIL
    BEATRICE BEATRIZ BELINDA BENITO BENNETT BENNIE BENNY BERNADETTE BERNARD
    BERNICE BERNIE BERT BERTHA BESSIE BETSY BETTE BETTIE BEULAH BHARAT BILL
    BILLIE BINH BLAINE BLAKE BLANCA BLANCHE BOBBIE BORIS BOYD BRAD BRADFORD
    BRADY BRANDI BRENDAN BRENNA BRENT BRETT BRIANNA BRIDGET BRIDGETTE BRITNEY
    BRITTNEY BRODY BRUNO BRYANT BRYCE BUDDY BURTON BUTCH BYRON CAITLIN CALEB
    CALLIE CALVIN CAMERON CAMILLE CANDACE CANDICE CARA CARISSA CARLA CARLENE
    CARLO CARLTON CARLY CAROLE CAROLINE CARRIE CARY CASEY CASSANDRA CASSIE
    CATHERINE CATHY CECELIA CECIL CECILIA CEDRIC CELESTE CELIA CESAR CHAD
    CHARLENE CHELSEA CHERI CHERIE CHESTER CHIRAG CHRISTA CHRISTI CHRISTIE
    CHRISTY CLARA CLARICE CLARK CLAUDE CLAUDETTE CLAUDIA CLEMENT CLEO CLETUS
    CLIFF CLIFFORD CLIFTON CLINT CLYDE CODY COLBY COLIN COLLEEN COLTON CONNOR
    CONRAD CONSTANCE CONSUELO CORA COREY CORINNE CORNELIUS CORNELL CORY
    COURTNEY CURT CYRIL CYRUS DALTON DAMIAN DAMON DANA DANE DANNIE DANTE DARCY
    DARIN DARIUS DARLA DARLENE DARNELL DARREL DARREN DARRIN DARRYL DARWIN DARYL
    DAVEY DAWN DEAN DEANA DEANDRE DEANN DEANNA DEANNE DEEPAK DEIDRE DELBERT
    DELIA DELLA DELMAR DELMER DELORES DEMETRIUS DENA DENNY DEREK DERICK DESIREE
    DESMOND DEVIN DEVON DEWAYNE DEWEY DEXTER DIEGO DILIP DINA DINESH DIRK
    DMITRI DOLORES DOMINGO DOMINIC DOMINICK DOMINIQUE DON DONNELL DONNY DONOVAN
    DORA DOREEN DOROTHEA DORTHY DOTTIE DOYLE DREW DUANE DUDLEY DUNG DUSTIN
    DUSTY DWAYNE DWIGHT EARLINE EARNEST ED EDDIE EDDY EDGAR EDITH EDMOND EDMUND
    EDNA EDWIN EDWINA EFFIE EFRAIN EILEEN ELAINE ELBERT ELDON ELEANOR ELI ELIAS
    ELIJAH ELINOR ELISA ELISABETH ELISE ELIZA ELLIOT ELLIOTT ELLIS ELMER ELOISE
    ELROY ELSA ELSIE ELTON ELVA ELVIN ELVIRA ELVIS ELWOOD EMANUEL EMIL EMILIA
    EMILIO EMMANUEL EMMETT EMORY ENOCH ERICA ERIK ERIKA ERMA ERNESTINE ERNESTO
    ERNIE ERROL ERVIN ERWIN ESTEBAN ESTELA ESTELLA ESTELLE ETTA EULA EUNICE EVA
    EVAN EVANGELINE EVE EVERETT EZEKIEL EZRA FABIAN FAISAL FANNIE FAYE FEDERICO
    FELICIA FELIPE FELIX FERDINAND FIDEL FLORA FLORENCE FLOYD FORREST FRANCES
    FRANCINE FRANKIE FRANKLIN FRANZ FREDA FREDDIE FREDDY FREDERICK FREDRICK
    FRIEDA FRITZ GAIL GALE GANESH GARRETT GARRY GARTH GAVIN GAYLE GAYLORD GENE
    GENEVIEVE GEORGETTE GEORGINA GERALD GERALDINE GERARD GERARDO GERHARD GERI
    GERTRUDE GIL GILBERT GILBERTO GILDA GINA GLADYS GLEN GLENDA GONZALO GORDON
    GRADY GRAHAM GRANT GRAYSON GREGG GREGORIO GRETA GRETCHEN GROVER GUILLERMO
    GUS GUSTAVO GUY GWEN GWENDOLYN HAI HAILEY HAL HALEY HALLIE HAMID HANK HANS
    HARLAN HARMON HARRIET HARVEY HATTIE HAYDEN HEATH HEIDI HELENA HELENE
    HENRIETTA HERMAN HERSCHEL HIEU HILARY HILDA HILLARY HOLLIS HOLLY HOMER
    HORACE HOYT HUBERT HUGH HUGO HUMBERTO HUSSEIN HYUN IAN IBRAHIM IDA IGNACIO
    IKE ILENE IMELDA IMOGENE INES INEZ INGRID IRA IRMA IRVIN IRVING IRWIN ISAAC
    ISABEL ISABELLE ISAIAH ISMAEL ISMAIL IVAN JACKIE JACLYN JACQUELYN JACQUES
    JAE JAGDISH JAIME JAKE JAMAL JAMI JAMIE JAN JANA JANELLE JANETTE JANIE
    JANINE JANIS JARED JAROD JARRETT JARVIS JASMINE JAY JAYDEN JAYESH JAYNE
    JEANETTE JEANIE JEANINE JEANNE JEANNETTE JEANNIE JED JENNA JENNIE JERALD
    JERI JERMAINE JEROME JERRI JESSIE JIAN JILLIAN JIMMIE JIN JO JOANIE JOANNA
    JOANNE JOAQUIN JOCELYN JODI JODIE JODY JOEL JOHANNA JOHNATHAN JOHNNIE
    JOLENE JONAH JONAS JONATHON JOSEF JOSEFINA JOSEPHINE JOSIAH JOSIE JOY JUANA
    JUANITA JUDE JULES JULIAN JULIANA JULIANNE JULIET JULIUS JUN JUNE KARA KARI
    KARIM KARL KARLA KARYN KATE KATELYN KATHARINE KATHERYN KATHI KATHIE KATRINA
    KAY KAYE KAYLEE KELLEY KELLI KELLIE KELSEY KELVIN KENDALL KENDRA KENNY KENT
    KERI KERMIT KERRI KETAN KHANH KIRAN KIRBY KIRK KORY KRISHNA KRISTA
    KRISTI KRISTIE KRISTINA KRISTINE KRISTY KURT KYLIE LACEY LAMAR LAMONT LANA
    LANCE LANDON LARS LATASHA LATONYA LATOYA LAURIE LAVERN LAVERNE LAVONNE
    LAYLA LAZARO LEANN LEANNA LEANNE LEE LEIGH LELA LELAND LENA LENORA LEO LEON
    LEONA LEONARDO LEONEL LESLIE LESTER LEVI LEWIS LIAM LILA LILIAN LILLIAN
    LILLIE LINDSAY LINDSEY LINH LIONEL LIZ LLOYD LOLA LONNIE LORA LOREN LORENA
    LORENZO LORETTA LORNA LORRAINE LOU LOUIE LOUISA LOURDES LOWELL LOYD LUANN
    LUCAS LUCILLE LUCINDA LUCY LUELLA LUKE LULA LUPE LUTHER LUZ LYDIA LYLE
    LYNDA LYNETTE LYNN LYNNE MABEL MACK MADELINE MADELYN MAE MAGDALENA MAGGIE
    MAHENDRA MAHESH MAHMOUD MAKAYLA MALCOLM MAMIE MANDY MANISH MANNY MANOJ MARC
    MARCEL MARCELLA MARCIA MARCO MARCOS MARCUS MARCY MARGIE MARGO MARGUERITE
    MARIAH MARIAN MARIANA MARIANNE MARIBEL MARICELA MARION MARISA MARISOL
    MARISSA MARJORIE MARK MARLA MARLENE MARLIN MARLON MARSHA MARSHALL MARTA
    MARTY MARVA MARYANN MARYANNE MARYELLEN MARYLOU MATEO MATHEW MATILDA MATTIE
    MAUDE MAURA MAUREEN MAURICE MAURICIO MAVIS MAX MAXINE MAXWELL MAYNARD MAYUR
    MEGHAN MELANIE MELBA MELINDA MELODY MELVA MEREDITH MERLE MERLIN MERRILL
    MERVIN MICAH MICHEAL MICHELE MICKEY MILES MILLIE MILO MILTON MINDY MINERVA
    MINNIE MIRANDA MIRIAM MISTY MITCH MITCHELL MITZI MOHAMMAD MOLLIE MOLLY MONA
    MONICA MONIQUE MONTE MONTY MORRIS MOSES MUKESH MURIEL MURRAY MUSTAFA
    MYRA MYRNA MYRON MYRTLE NABIL NADIA NADINE NAM NANETTE NAOMI NARENDRA
    NARESH NASSER NATASHA NATHANIEL NAVIN NEAL NED NEIL NELDA NELL NELLIE
    NELSON NESTOR NETTIE NEWTON NICHOLE NICOLAS NIGEL NIKHIL NILES NILESH NINA
    NITA NITIN NOEL NOELLE NOEMI NOLAN NONA NORA NORBERT NOREEN NORRIS OCTAVIO
    ODELL OFELIA OLA OLGA OLIVER OLLIE ORLANDO ORVAL ORVILLE OSWALDO OTIS OTTO
    OWEN PABLO PAIGE PAM PANKAJ PARESH PASQUALE PAT PATRICE PATSY PATTI
    PAULETTE PAULINE PEARLIE PENELOPE PERCY PERRY PEYTON PHIL PHOEBE PHONG
    PHUONG PIERRE PIOTR PIYUSH POLLY PRADEEP PRAKASH PRAVIN PRESTON PRISCILLA
    QUANG QUENTIN QUINTON RACHAEL RAJESH RAJIV RAKESH RAMIRO RAMONA RANDAL
    RANDALL RANDOLPH RAQUEL RASHID RAY RAYMOND REBA REBEKAH REGGIE REGINA
    REGINALD REID RENA RENE RENEE REUBEN REX REYNALDO RHODA RHONDA RICH RICHIE
    RICKIE RIGOBERTO RILEY RITA ROB ROBBIE ROBERTA ROBYN ROCCO ROCHELLE ROCKY
    ROD RODERICK RODGER RODOLFO RODRIGO ROGELIO ROHIT ROLAND ROLANDO ROLLAND
    ROMAN ROMEO RONNIE ROOSEVELT ROSALIE ROSALIND ROSALYN ROSANNA ROSANNE
    ROSCOE ROSEANN ROSEMARIE ROSEMARY ROSETTA ROSIE ROSS ROWENA ROXANNE ROXIE
    RUBEN RUDOLPH RUDY RUFUS RUPERT RUSS RUSTY RUTHIE SABRINA SACHIN SADIE SAL
    SALEH SALLIE SALVADOR SAMI SAMIR SAMMY SANDI SANJEEV SANTIAGO SANTOSH
    SATISH SAUL SEBASTIAN SELENA SERENA SERGEI SETH SEUNG SEYMOUR SHANA SHANE
    SHANKAR SHANNA SHANNON SHARI SHARLENE SHAUN SHAWNA SHEENA SHELDON SHELIA
    SHELLEY SHELLY SHELTON SHERI SHERMAN SHERRI SHERRIE SHERYL SHYAM SID SIDNEY
    SILAS SIMON SIMONE SOCORRO SOFIA SOLOMON SONDRA SONIA SONJA SONNY SONYA
    SOPHIE STAN STEFAN STELLA STEWART STUART SUBHASH SUNIL SUSANA SUSANNE SUSIE
    SUZANNE SUZETTE SYBIL SYLVESTER SYLVIA TABATHA TABITHA TADEUSZ TAMARA
    TAMEKA TAMI TAMIKA TAMMIE TANIA TANYA TARA TARIQ TASHA TED TEDDY TERENCE
    TERI TERRANCE TERRELL TERRENCE TERRI TESSA THADDEUS THANH THAO THELMA
    THEODORA THEODORE THURMAN THUY TOBY TOMAS TOMMIE TONI TONIA TONYA TRACI
    TRACIE TRENT TREVOR TREY TRICIA TRINA TRISHA TRISTAN TROY TRUDY TRUMAN
    TRUNG TUNG TYRONE TYSON ULYSSES UMESH URSULA VALARIE VALERIE VANESSA VAUGHN
    VELMA VERA VERLE VERN VERNA VERNE VERNON VICENTE VICKY VIKRAM VINCE VINH
    VINOD VIOLA VIPUL VIRGIL VIVIAN VLADIMIR WADE WALDO WALID WALLACE WALT
    WARREN WELDON WENDELL WENDI WENDY WES WESLEY WILBERT WILBUR WILEY WILFORD
    WILFRED WILFREDO WILLA WILLARD WILLIS WILMA WILMER WINFIELD WINIFRED WINNIE
    WINSTON WOODROW WOODY WYATT XAVIER XIAO YESENIA YOGESH YONG YOUSEF YURI
    YUSUF YVETTE YVONNE ZACH ZANE ZEKE ZELDA ZELMA
    """.split()
)

# Organization, business, facility, government, and place words. A name that
# carries any of them is not treated as a bare personal name. FAMILY, TRUST,
# ESTATE, and PROPERTY are deliberately absent because they commonly qualify a
# personal name, and PA is absent because it is also a state code.
_NOT_A_PERSON = frozenset(
    """
    LLC INC CORP CO COMPANY COS LTD LP LLP PLLC PC DBA FOUNDATION ASSOC ASSN
    ASSOCIATION ASSOCIATES SOCIETY CLUB CHURCH MINISTRIES MINISTRY TEMPLE
    SYNAGOGUE MOSQUE PARISH DIOCESE SCHOOL SCHOOLS ACADEMY COLLEGE UNIVERSITY
    UNIV INSTITUTE HOSPITAL MEDICAL HEALTH HEALTHCARE CLINIC CARE CENTER CENTRE
    CTR PHARMACY DRUG DRUGS STORE STORES SHOP SHOPPE SHOPS MARKET MARKETS MART
    SUPERMARKET FOOD FOODS GROCERY RESTAURANT CAFE DINER BAKERY DELI GRILL PIZZA
    BAR TAVERN PUB HOTEL MOTEL INN RESORT LODGE CAMP CAMPGROUND MARINA GOLF
    COUNTRY PLANT FACILITY MILL MILLS FACTORY WORKS MFG MANUFACTURING
    INDUSTRIES INDUSTRIAL IND PRODUCTS PRODUCT SUPPLY SUPPLIES EQUIPMENT MACHINE
    MACHINERY TOOL TOOLS METAL METALS STEEL IRON FOUNDRY PLASTICS CHEMICAL
    CHEMICALS PAPER PRINTING PRESS ELECTRIC ELECTRICAL ELECTRONICS POWER ENERGY
    GAS OIL PETROLEUM FUEL FUELS PROPANE SOLAR WIND UTILITY UTILITIES WATER
    WASTEWATER SEWER SEWAGE TREATMENT WWTP WTP STP POTW WWTF WRF LANDFILL
    RECYCLING SALVAGE SCRAP DISPOSAL SANITATION ENVIRONMENTAL WASTE AUTO
    AUTOMOTIVE MOTOR MOTORS CAR CARS TRUCK TRUCKS TRUCKING TRANSPORT
    TRANSPORTATION TRANSIT LOGISTICS FREIGHT EXPRESS HAULING DELIVERY MOVING
    STORAGE WAREHOUSE DISTRIBUTION SALES SERVICE SERVICES SVC SVCS SOLUTIONS
    SYSTEMS TECHNOLOGIES TECHNOLOGY TECH ENTERPRISES ENTERPRISE GROUP HOLDINGS
    PARTNERS PARTNERSHIP VENTURES INTERNATIONAL INTL NATIONAL AMERICAN AMERICA
    USA US UNITED GLOBAL CONSTRUCTION CONTRACTING CONTRACTORS BUILDERS BUILDING
    BLDG HOMES REALTY PROPERTIES DEVELOPMENT MANAGEMENT MGMT CONSULTING
    ENGINEERING LAB LABS LABORATORY LABORATORIES BODY PAINT COLLISION REPAIR
    TIRE TIRES LUBE WASH CLEANERS CLEANING LAUNDRY DENTAL VETERINARY ANIMAL SONS
    BROS BROTHERS CITY TOWN TOWNSHIP TWP VILLAGE BOROUGH COUNTY STATE DEPT
    DEPARTMENT AUTHORITY DISTRICT COMMISSION BOARD PUBLIC MUNICIPAL FEDERAL ARMY
    NAVY FORCE BASE FIRE POLICE STATION CORRECTIONAL PRISON JAIL LIBRARY PARK
    PARKS AIRPORT PORT HARBOR RIVER LAKE LAKES CREEK MOUNTAIN MTN VALLEY HILL
    HILLS RIDGE SPRINGS SPRING POINT ISLAND BEACH BAY HEIGHTS WOODS FOREST GROVE
    MEADOWS ESTATES SQUARE PLAZA MALL CROSSING COMMONS TOWER TOWERS APARTMENTS
    APTS MHP MOBILE SUBDIVISION SECTION PHASE MINE MINING QUARRY PIT SAND GRAVEL
    STONE ROCK TIMBER LOGGING LUMBER WOOD TERMINAL YARD DEPOT SITE PROJECT UNIT
    WELL WELLS TANK PIPELINE COMPRESSOR SUBSTATION GENERATING CONDO CONDOMINIUM
    HOA OWNERS INVESTMENTS CAPITAL FUND BANK FINANCIAL INSURANCE AGENCY OFFICE
    RETAIL OUTLET DEALERSHIP FORD CHEVROLET CHEVY TOYOTA HONDA NISSAN KIA
    HYUNDAI DODGE JEEP CHRYSLER BUICK GMC CADILLAC SUBARU MAZDA LEXUS BMW
    MERCEDES VOLKSWAGEN AUDI CONCRETE ASPHALT PAVING EXCAVATING LANDSCAPING
    LANDSCAPE LAWN TREE PLUMBING HEATING HVAC ROOFING MASONRY WELDING
    FABRICATION FAB CUSTOM CABINET FURNITURE GLASS FUNERAL CEMETERY CREMATORY
    MEMORIAL NURSING REHAB ASSISTED LIVING SENIOR COMMUNITY CHILDREN KIDS
    DAYCARE BAPTIST METHODIST LUTHERAN CATHOLIC PRESBYTERIAN EPISCOPAL CHRISTIAN
    FIRST SAINT ST ROUTE RT HWY HIGHWAY NORTH SOUTH EAST WEST NORTHERN SOUTHERN
    EASTERN WESTERN CENTRAL NEW OLD GREAT BIG LITTLE THE OF AT IN ON FOR REAL
    MANOR VILLAS VILLA GARDENS GARDEN HOUSING CORPORATION INCORPORATED GENERAL
    DOLLAR TOWNHOMES ROAD RD LAGOON COMPLEX LANDING MATERIALS WWSL CAFO WPCF
    WPCP PACKAGING MIX CLNR PLACE COVE POINTE MARINE UPS BORO STRIP HAULROAD
    SUITES STREET FAC RESERVE EXPANSION LOADOUT CAMPUS AUTH BRANCH OAKS
    DIVISION HOSP DRIVE SD
    FARM FARMS DAIRY DAIRIES ORCHARD ORCHARDS NURSERY NURSERIES GREENHOUSE
    GREENHOUSES POULTRY HOG HOGS CATTLE LIVESTOCK RANCH FEEDLOT VINEYARD
    VINEYARDS BARN ACRES PRODUCE
    """.split()
)

# Place prefixes and facility words that stop only the wider shapes (an
# initial, "SURNAME GIVEN", a dwelling word, a personal trust or estate), so
# that names such as "SAN JOSE", "FORT JANE", or "CIRCLE Q" are not read as a
# person. They are kept out of _NOT_A_PERSON so they never admit a name that
# the narrower shapes reject.
_WIDER_SHAPE_STOP_WORDS = _NOT_A_PERSON | frozenset(
    """
    SAN SANTA SANTO FORT MOUNT MT CAPE STE SAINTE
    TRACT PAD CELL BASIN OUTFALL ZONE DAM DOCK PIER CIRCLE
    """.split()
)

_CONJUNCTIONS = frozenset({"&", "AND"})


def _tokens(text: str) -> list[str]:
    text = text.replace(".", "").replace("&", " & ")
    return [
        token.strip("'-")
        for token in _TOKEN_SPLIT.split(text)
        if token.strip("'-")
    ]


def _without_possessive(token: str) -> str:
    return token[:-2] if token.endswith("'S") and len(token) > 2 else token


def _is_given(word: str) -> bool:
    return word in _GIVEN_NAMES or word.split("-", 1)[0] in _GIVEN_NAMES


def _first_given(segment: str) -> bool:
    words = [
        _without_possessive(token)
        for token in _tokens(segment)
        if token not in _NAME_AFFIXES and token not in _CONJUNCTIONS
    ]
    return bool(words) and _is_given(words[0])


def _initials_only(segment: str) -> bool:
    words = [token for token in _tokens(segment) if token not in _NAME_AFFIXES]
    return 1 <= len(words) <= 3 and all(
        len(word) == 1 and word.isalpha() for word in words
    )


def _person_shaped(upper: str) -> bool:
    """True for a bare personal or household name with no organization word."""

    head = _ESTATE_OF.sub("", _DBA.sub("", upper)).strip()
    honorific = _HONORIFIC.match(head)
    if honorific:
        head = head[honorific.end():]
    head = _ORDINAL_AFFIX.sub(" ", head).strip()
    if not head or _DIGIT.search(head):
        return False
    tokens = [token for token in _tokens(head) if token not in _NAME_AFFIXES]
    while tokens and tokens[-1] in _SEPTIC_DESCRIPTORS:
        tokens.pop()
    if not tokens or any(
        _without_possessive(token) in _NOT_A_PERSON for token in tokens
    ):
        return False
    has_conjunction = any(token in _CONJUNCTIONS for token in tokens)
    words = [
        _without_possessive(token)
        for token in tokens
        if token not in _CONJUNCTIONS
    ]
    if not words or not all(_NAME_WORD.fullmatch(word) for word in words):
        return False
    if honorific:
        return len(words) <= 6  # "MR SAMPLE", "MR & MRS JANE SAMPLE"
    if not 2 <= len(words) <= (10 if has_conjunction else 7):
        return False
    if _is_given(words[0]):
        return True
    parts = head.split(",")
    if len(parts) == 2 and _first_given(parts[1]):
        return True  # "SURNAME, GIVEN"
    if has_conjunction and any(_is_given(word) for word in words[:2]):
        return True
    # Wider shapes. A place prefix or facility word stops them.
    if any(word in _WIDER_SHAPE_STOP_WORDS for word in words):
        return False
    if len(parts) == 2 and _initials_only(parts[1]):
        return True  # "SURNAME, I"
    if any(len(word) == 1 for word in words) and any(len(word) > 1 for word in words):
        return True  # an initial: "GIVEN I SURNAME", "I SURNAME", "SURNAME I"
    # "SURNAME GIVEN" or "SURNAME GIVEN GIVEN" without a comma.
    return _is_given(words[1]) and all(_is_given(word) for word in words[2:])


def _marked_person(upper: str) -> bool:
    """True for a personal trust, estate, heirs, or et al. designation."""

    head = _DBA.sub("", upper)
    if not _PERSON_MARKER.search(head):
        return False
    rest = _LEADING_THE.sub("", _PERSON_MARKER.sub(" ", head))
    words = [
        _without_possessive(token)
        for token in _tokens(rest)
        if token not in _NAME_AFFIXES and token not in _CONJUNCTIONS
    ]
    return (
        bool(words)
        and not _DIGIT.search(rest)
        and not any(word in _WIDER_SHAPE_STOP_WORDS for word in words)
    )


def _residence_word_name(upper: str) -> bool:
    """True for a dwelling word with at most three other non-organization words."""

    tokens = [_without_possessive(token) for token in _tokens(_DBA.sub("", upper))]
    if not any(token in _RESIDENCE_WORDS for token in tokens):
        return False
    rest = [
        token
        for token in tokens
        if token not in _RESIDENCE_WORDS and token not in _CONJUNCTIONS
    ]
    return len(rest) <= 3 and not any(
        token in _WIDER_SHAPE_STOP_WORDS for token in rest
    )


def _has_organization_marker(upper: str) -> bool:
    if _GOVERNMENT_OF.search(upper):
        return True
    return any(token in _ORGANIZATION_MARKERS for token in _tokens(upper))


def excluded_name_reason(
    name: str, naics_codes: Iterable[str] = ()
) -> str | None:
    """Return why a facility row must be excluded, or ``None`` to admit it.

    Codes: ``PRIVATE_HOUSEHOLD_NAICS``, ``STREET_ADDRESS_IN_NAME``,
    ``RESIDENTIAL_PERMIT_NAME``, ``PERSON_SHAPED_NAME``. The returned code
    never contains any part of the name.
    """

    if PRIVATE_HOUSEHOLD_NAICS in naics_codes:
        return "PRIVATE_HOUSEHOLD_NAICS"
    upper = " ".join(str(name or "").upper().split())
    if not upper:
        return None
    if _STREET_ADDRESS.search(upper) or _ROUTE_ADDRESS.search(upper):
        return "STREET_ADDRESS_IN_NAME"
    if _RESIDENTIAL.search(upper) and not _has_organization_marker(upper):
        return "RESIDENTIAL_PERMIT_NAME"
    if _residence_word_name(upper):
        return "RESIDENTIAL_PERMIT_NAME"
    if _person_shaped(upper) or _marked_person(upper):
        return "PERSON_SHAPED_NAME"
    return None
